### ISSUE TITLE
Error running server project on Linux (pop_os)

### ISSUE THREAD

**Issue by supermacro** [parlez-vous/server#108]
![Screenshot from 2021-03-13 13-10-06](https://user-images.githubusercontent.com/10621548/115122808-ec5f4500-9f87-11eb-9db1-61998dc745f5.png)

Could be something basic that I am missing as I am new with docker on linux. Searched for solutions but could not find anything that works. 

For running on linux, had to comment out the volume mapping going on in docker-compose.yml 

![image](https://user-images.githubusercontent.com/10621548/115122821-ff721500-9f87-11eb-9480-a42342c58ce8.png)

**Comment by supermacro** [comment]
From @aszenz

> I'm running the server locally , while postgres is run via docker. It's much easier that way. Just install nodejs 14, and setup NODE_PATH=./build, before running npm start

**Comment by aszenz** [comment]
@supermacro This should be fixed now by #109.

The docker setup is still not ideal, especially for development but at least it should work properly now
